### ISSUE TITLE
Incorrect statement in js

### ISSUE THREAD

**Issue by fredrikbondesson** [rowanthorpe/ws-repl#1]
https://github.com/rowanthorpe/ws-repl/blob/55d2899646e1cba7a144186ee0c2ce1718bcbb7d/ws-repl.js#L54

Should be var mainEl  = document.getElementById(arg.widgetName);

**Comment by rowanthorpe** [comment]
Many thanks for pointing this out, and sorry for the delay responding - "real life" doesn't allow me on to my personal project repos much these days [cue sad-violin]. Am pushing a commit now to fix and close this.
